server:
  port: 8080

    
product:
  service:
    api:
      url:
        add: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/products/auth/add-product-imgs
        delete: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/products/auth/delete-product/
        update: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/products/auth/update-product/
        update_active: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/products/auth/update-active/byid/
        getbyid: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/products/get/product-res/
        change-quantity-byid: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/products/auth/change-quantity/

brand:
  service:
    api:
      url:
        add: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/brands/auth/add
        delete: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/brands/auth/delete/
        update: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/brands/auth/update/
         
category:
  service:
    api:
      url:
        add: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/categories/auth/add
        delete: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/categories/auth/delete/
        update: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/categories/auth/update/
         
banner:
  service:
    api:
      url:
        add: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/banners/auth/save
        delete: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/banners/auth/delete/byid/
        update: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/banners/auth/update/ 
        update_enabled: ${PRODUCT_APP_DOMAIN}/products/pckart/api/v1/banners/auth/update/enabled/


user:
  service:
    api:
      url:
        getall: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/user/get/allUsers
        getbyid: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/user/getbyid/
        update_nonlocked: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/user/update/nonlocked/byid/

order:
  service:
    api:
      url:
        getall: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/get/allOrders
        getall_bylimit: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/get/orders/bylimit/
        getbyid: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/get/order/byid/
        getbyUserid: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/get/orders/byUserId/
        getbyTrackingNo: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/get/order/byTrackingNo/
        update_order_status: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/update/order_status/byid/
        update_payment_status: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/update/payment_status/byid/
        update_track_status: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/update/track_status/byid/
        get_orders_page: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/get/orders-page/
        update_return_order: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/order/update/return-order
        

payment:
  service:
    api:
      url:
        credit: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/payment/credit/byUserId/
        
coupon:
  service:
    api:
      url:
        save: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/coupon/save
        getall: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/coupon/get/coupon/all
        getbyid: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/coupon/get/coupon/byid/
        update_coupondata: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/coupon/update/coupondata/byid/
        update_validupto_discount: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/coupon/update/validupto_discount/byid/
        update_enabled: ${USER_APP_DOMAIN}/users/pckart/api/v1/user-to-admin/coupon/update/enabled/byid/
       
cors:
  set:
    allowed:
      origins: ${CORS_ALLOWED_ORIGINS}
     
jwt:
  secret:
    key:
      admins: ${JWT_ADMINS_TOKEN}
      expiration: 604800000  # for a day 86400000
      users: ${JWT_USERS_TOKEN}
      products: ${JWT_PRODUCTS_TOKEN}
      payments: ${JWT_PAYMENTS_TOKEN}






      

    